/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as StockMarketSymbolRouteImport } from './routes/stock.$market.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StockMarketSymbolRoute = StockMarketSymbolRouteImport.update({
  id: '/stock/$market/$symbol',
  path: '/stock/$market/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/stock/$market/$symbol': typeof StockMarketSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/stock/$market/$symbol': typeof StockMarketSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/stock/$market/$symbol': typeof StockMarketSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/backtest'
    | '/compare'
    | '/notes'
    | '/portfolio'
    | '/screener'
    | '/settings'
    | '/watchlist'
    | '/stock/$market/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/backtest'
    | '/compare'
    | '/notes'
    | '/portfolio'
    | '/screener'
    | '/settings'
    | '/watchlist'
    | '/stock/$market/$symbol'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/backtest'
    | '/compare'
    | '/notes'
    | '/portfolio'
    | '/screener'
    | '/settings'
    | '/watchlist'
    | '/stock/$market/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  BacktestRoute: typeof BacktestRoute
  CompareRoute: typeof CompareRoute
  NotesRoute: typeof NotesRoute
  PortfolioRoute: typeof PortfolioRoute
  ScreenerRoute: typeof ScreenerRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  StockMarketSymbolRoute: typeof StockMarketSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$market/$symbol': {
      id: '/stock/$market/$symbol'
      path: '/stock/$market/$symbol'
      fullPath: '/stock/$market/$symbol'
      preLoaderRoute: typeof StockMarketSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  BacktestRoute: BacktestRoute,
  CompareRoute: CompareRoute,
  NotesRoute: NotesRoute,
  PortfolioRoute: PortfolioRoute,
  ScreenerRoute: ScreenerRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  StockMarketSymbolRoute: StockMarketSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
