export interface SourceCapability {
  id: string;
  name: string;
  officialUrl: string;
  markets: string[];
  products: string[];
  latency: "realtime" | "delayed" | "after_hours";
  history: string;
  timeframes: string[];
  timezone: string;
  update: string;
  apiKey: string;
  fee: string;
  quota: string;
  redistribution: string;
  verifiedAt: string;
  wired: boolean;
  notes: string;
}

export const SOURCE_CATALOG: SourceCapability[] = [
  {
    id: "twse-openapi",
    name: "臺灣證券交易所 OpenAPI",
    officialUrl: "https://openapi.twse.com.tw/",
    markets: ["TWSE"],
    products: ["上市股票", "ETF", "估值", "月營收", "公司基本資料", "除權息"],
    latency: "after_hours",
    history: "多數端點僅最新一期快照，無歷史區間參數（2026-09-06 實測 STOCK_DAY_ALL 加 date 無效）",
    timeframes: ["1D"],
    timezone: "Asia/Taipei",
    update: "盤後批次；OpenAPI 有時較官網 JSON 晚一日",
    apiKey: "不需要",
    fee: "免費開放資料",
    quota: "未公布固定額度；實務需自律限速",
    redistribution: "公開開放資料，商用再散布仍應遵守證交所開放資料條款，本 APP 僅供研究展示、不轉售行情",
    verifiedAt: "2026-09-06",
    wired: true,
    notes: "已接通 STOCK_DAY_ALL、BWIBBU_ALL、t187ap03_L、t187ap05_L、TWT48U_ALL。",
  },
  {
    id: "twse-rwd",
    name: "臺灣證券交易所官網盤後 JSON（rwd）",
    officialUrl: "https://www.twse.com.tw/",
    markets: ["TWSE"],
    products: ["加權指數", "個股日成交（可按月）", "三大法人", "融資融券", "漲跌家數", "成交量排行", "休市日"],
    latency: "after_hours",
    history: "STOCK_DAY 可按年月回溯個股日 K；FMTQIK 當月市場成交；MI_INDEX 指定日期",
    timeframes: ["1D"],
    timezone: "Asia/Taipei",
    update: "收盤後當日下午起可取得",
    apiKey: "不需要",
    fee: "官網公開查詢",
    quota: "未公布；需限速與快取，禁止高頻輪詢",
    redistribution: "取自公開網頁查詢 API，僅供本機研究，不得偽裝為即時行情商用轉售",
    verifiedAt: "2026-09-06",
    wired: true,
    notes: "歷史日 K 主來源。2026-09-06 實測 2330 2026-09 回傳 ROC 日期欄。",
  },
  {
    id: "tpex-openapi",
    name: "證券櫃檯買賣中心 OpenAPI",
    officialUrl: "https://www.tpex.org.tw/openapi/",
    markets: ["TPEX"],
    products: ["上櫃收盤", "本益比／殖利率", "三大法人", "公司基本資料"],
    latency: "after_hours",
    history: "OpenAPI 多為最新快照",
    timeframes: ["1D"],
    timezone: "Asia/Taipei",
    update: "盤後",
    apiKey: "不需要",
    fee: "免費開放資料",
    quota: "未公布；自律限速",
    redistribution: "遵守櫃買中心開放資料使用條款；本 APP 不轉售",
    verifiedAt: "2026-09-06",
    wired: true,
    notes: "tpex_mainboard_quotes、tpex_mainboard_peratio_analysis、tpex_3insti_daily_trading、mopsfin_t187ap03_O。",
  },
  {
    id: "tpex-rwd",
    name: "櫃買中心官網個股日成交 JSON",
    officialUrl: "https://www.tpex.org.tw/",
    markets: ["TPEX"],
    products: ["上櫃個股日 K（按月）"],
    latency: "after_hours",
    history: "tradingStock?code=&date=yyyy/mm/01 可取該月日 K（2026-09-06 實測 6488）",
    timeframes: ["1D"],
    timezone: "Asia/Taipei",
    update: "盤後",
    apiKey: "不需要",
    fee: "官網公開查詢",
    quota: "未公布；需限速",
    redistribution: "公開查詢資料，僅供研究",
    verifiedAt: "2026-09-06",
    wired: true,
    notes: "date 必須為該月任一日 yyyy/mm/dd；yyyy/mm 會回參數錯誤。",
  },
  {
    id: "mis",
    name: "證交所 MIS 盤中報價",
    officialUrl: "https://mis.twse.com.tw/",
    markets: ["TWSE", "TPEX"],
    products: ["盤中延遲報價"],
    latency: "delayed",
    history: "無",
    timeframes: ["tick"],
    timezone: "Asia/Taipei",
    update: "盤中",
    apiKey: "非正式開放 API",
    fee: "未取得轉授權",
    quota: "—",
    redistribution: "第一版未接入；未驗證商用授權",
    verifiedAt: "2026-09-06",
    wired: false,
    notes: "尚未具備即時來源授權，畫面固定標示盤後／延遲模式。",
  },
  {
    id: "finmind",
    name: "FinMind",
    officialUrl: "https://finmindtrade.com/",
    markets: ["TWSE", "TPEX"],
    products: ["歷史價、財報、籌碼、新聞（視方案）"],
    latency: "after_hours",
    history: "依方案",
    timeframes: ["1D", "部分分 K"],
    timezone: "Asia/Taipei",
    update: "依方案",
    apiKey: "需要 token",
    fee: "免費額度 + 付費方案，未在本環境驗證額度",
    quota: "未驗證",
    redistribution: "依 FinMind 條款，禁止臆測",
    verifiedAt: "2026-09-06",
    wired: false,
    notes: "Adapter 預留於設定，未宣稱已連線。",
  },
  {
    id: "us-equities",
    name: "美股行情",
    officialUrl: "",
    markets: ["US"],
    products: ["美股"],
    latency: "delayed",
    history: "未查證",
    timeframes: [],
    timezone: "America/New_York",
    update: "—",
    apiKey: "—",
    fee: "—",
    quota: "—",
    redistribution: "擴充階段另行查證",
    verifiedAt: "2026-09-06",
    wired: false,
    notes: "架構預留 Market 型別擴充，第一版不提供。",
  },
];
